import numpy as np
import panel as pn
import matplotlib.pyplot as plt
import hvplot.pandas
import glob 
import os, sys
import pandas as pd
from natsort import natsorted

## Interactive dashboard to browse pulse and difference profiles generated by bandshape.equalization.py.  
#loading all the files required to plot

# provide relative path wrt to the notebook/script
threshold = sys.argv[1]
nchan = sys.argv[2]

path = 'threshold_'+str(threshold)+'/nchan_'+str(nchan)

file_area_NP_path = path+'/Files/Norm_area_method/'
file_peak_NP_path = path+'/Files/Norm_peak_method/'


# load files to dataframes
file_area_NP_list = natsorted([file_area_NP_path + f for f in os.listdir(file_area_NP_path) if f.startswith('Norm')])
file_area_Pdiff_list = natsorted([file_area_NP_path + f for f in os.listdir(file_area_NP_path) if f.startswith('Profile')])
file_peak_NP_list = natsorted([file_peak_NP_path + f for f in os.listdir(file_peak_NP_path) if f.startswith('Norm')])
file_peak_Pdiff_list = natsorted([file_peak_NP_path + f for f in os.listdir(file_peak_NP_path) if f.startswith('Profile')])

# functions to prep the dataframes
def create_NP_df(file_list):
    main_dataframe = pd.DataFrame(pd.read_csv(file_list[0]))
    for i in file_list:
        df = pd.read_csv(i)
        df = df.fillna(0)
        col_name = i.split('_')[6].split('.')[0]	
        index = next(i for i, char in enumerate(col_name) if char.isdigit())
        numbers = col_name[index:]
        padcol= f'{int(numbers):03}'
        df.columns = [padcol]
        main_dataframe = pd.concat([main_dataframe,df],axis=1)
    main_dataframe.drop(main_dataframe.columns[0], axis=1, inplace=True)
    main_dataframe.sort_index(inplace = True, axis = 1)
    return main_dataframe

def create_Pdiff_df(file_list):
    main_dataframe = pd.DataFrame(pd.read_csv(file_list[0]))
    for i in file_list:
        df = pd.read_csv(i)
        df = df.fillna(0)
        col_name = str('subband ') + str(i.split('_')[7]+'-'+str(int(i.split('_')[7])+1))
        parts = col_name.split()
        numbers = parts[1]
        start, end = numbers.split('-')
        pad_range = f'{int(start):03}-{int(end):03}'
        df.columns = [pad_range]
        main_dataframe = pd.concat([main_dataframe,df],axis=1)
    main_dataframe.drop(main_dataframe.columns[0], axis=1, inplace=True)
    main_dataframe.sort_index(inplace = True, axis = 1)
    return main_dataframe

# Make DataFrame Pipeline Interactive
normProf_A_df = create_NP_df(file_area_NP_list)
normProf_P_df = create_NP_df(file_peak_NP_list)
Pdiff_A_df = create_Pdiff_df(file_area_Pdiff_list)
Pdiff_P_df = create_Pdiff_df(file_peak_Pdiff_list)

iNP_A_df = normProf_A_df.interactive()
iNP_P_df = normProf_P_df.interactive()
ipdiff_A_df = Pdiff_A_df.interactive()
ipdiff_P_df = Pdiff_P_df.interactive()

# Define Panel widgets
end = len(file_area_Pdiff_list)
#subband_slider = pn.widgets.IntSlider(name='subband_slider', start=0, end=end, step=1, value=10)
subband_slider = pn.widgets.IntInput(name='Value Stepper', value=5, step=1, start=0, end=end)
#subband_slider = pn.widgets.DiscreteSlider(name='subband_slider', options=list(range(0, end, 1)), value=10)
area_inp = iNP_A_df.iloc[:,subband_slider].hvplot(color="steelblue")
profile_inp = iNP_P_df.iloc[:,subband_slider].hvplot(color="teal",yaxis="left")
area_diff = ipdiff_A_df.iloc[:,subband_slider].hvplot(color="#fc4f30")
profile_diff = ipdiff_P_df.iloc[:,subband_slider].hvplot(color="#e5ae38",yaxis="left")

# Function to stop the server and exit
def exit_dashboard(event=None):
    sys.exit() #You can also use sys.exit() or os._exit() if needed

# Create the exit button
exit_button = pn.widgets.Button(name='Exit', button_type='danger')

# Link the button click event to the exit function
exit_button.on_click(exit_dashboard)


# Add JavaScript to close the browser tab
close_tab_js = """
window.close();
"""

# Button that triggers the JavaScript to close the tab
close_button = pn.widgets.Button(name='Close Tab', button_type='primary')
close_button.js_on_click(args={}, code=close_tab_js)

#Create dashboard using template
template = pn.template.FastListTemplate(
    title='NB Timing tests ', 
    sidebar=[pn.pane.Markdown("# Tests to determine the number of subbands"), 
             pn.pane.Markdown("## In the app interface, you'll find two rows. \
             The first subplot in the upper row illustrates 'Normalization by Area' and 'Normalization by Peak,' \
             with an interactive slider. Slide it left or right to dynamically compare these plots.\
             The second subplot illustrates the difference between subbands {subands[i] - subands[i+1]} for both normalizations, \
             and the slider allows for easy comparison.\
             "),            
             pn.pane.Markdown("#### NOTE: All sliders are active, and each slider adjustment simultaneously updates the same instance in both plots. \
             Currently, the states of all sliders are not synchornized. Please ignore."),
             pn.pane.Markdown("#### Explore and analyze your data effortlessly using these interactive features!")], 
    main=[pn.Row(pn.Column('## Normalization by Area/Peak', pn.Swipe(area_inp, profile_inp),sizing_mode='scale_both'),
                 pn.Column('## Normalization by Area/Peak - Difference', pn.Swipe(area_diff, profile_diff),sizing_mode='scale_both')
                ),
          pn.Row(pn.pane.Markdown("### Click 'Exit' to stop the server, then 'Close Tab' to close the browser."), exit_button, close_button)
         ],
    accent_base_color="#88d8b0",
    header_background="#88d8b0",
)

template.show()
template.servable();
